// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-CCADxIV5-KGq1CbfXpUXC3GyCaSHqQ',
    appId: '1:300449604334:web:a3f316239d38b13c2349ff',
    messagingSenderId: '300449604334',
    projectId: 'zim-tracker-bce22',
    authDomain: 'zim-tracker-bce22.firebaseapp.com',
    storageBucket: 'zim-tracker-bce22.firebasestorage.app',
    measurementId: 'G-3BQ9286106',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvbvZfUZHvYEzkWLx-39VOBmIw_LVao8',
    appId: '1:300449604334:android:1112da1aeade88c22349ff',
    messagingSenderId: '300449604334',
    projectId: 'zim-tracker-bce22',
    storageBucket: 'zim-tracker-bce22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcBg3J_ctzDt7gwUmMVz-EK7G3XTIs6UI',
    appId: '1:300449604334:ios:c3da72f60bae56cd2349ff',
    messagingSenderId: '300449604334',
    projectId: 'zim-tracker-bce22',
    storageBucket: 'zim-tracker-bce22.firebasestorage.app',
    iosClientId: '300449604334-2ef36rdtik9taglhqklagec2tv1fngmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zimTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcBg3J_ctzDt7gwUmMVz-EK7G3XTIs6UI',
    appId: '1:300449604334:ios:c3da72f60bae56cd2349ff',
    messagingSenderId: '300449604334',
    projectId: 'zim-tracker-bce22',
    storageBucket: 'zim-tracker-bce22.firebasestorage.app',
    iosClientId: '300449604334-2ef36rdtik9taglhqklagec2tv1fngmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zimTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3-CCADxIV5-KGq1CbfXpUXC3GyCaSHqQ',
    appId: '1:300449604334:web:eff02947e44200652349ff',
    messagingSenderId: '300449604334',
    projectId: 'zim-tracker-bce22',
    authDomain: 'zim-tracker-bce22.firebaseapp.com',
    storageBucket: 'zim-tracker-bce22.firebasestorage.app',
    measurementId: 'G-VVZK35DYFW',
  );
}
